framework:
    messenger:
        default_bus: event.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - validation
                    # Custom middleware to clear stateful doctrine services
                    - App\Common\Infrastructure\Bus\Middleware\DoctrineClearMiddleware
                    - dispatch_after_current_bus
                    - doctrine_open_transaction_logger
                    # Wraps all handlers in a single doctrine transaction.
                    - App\Common\Infrastructure\Bus\Middleware\DoctrineTransactionMiddleware
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        failure_transport: failed
        transports:
            failed: 'doctrine://default?table_name=messenger_messages&queue_name=failed'
            sync: 'sync://'
            event_store:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                options:
                    exchange:
                        name: event_store_exchange
                    queues:
                        messages_event_store: ~
                    confirm_timeout: 10
        routing: