# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # Bus
    App\Common\Infrastructure\Bus\Event\SymfonyEventBus:
        class: App\Common\Infrastructure\Bus\Event\SymfonyEventBus
        arguments:
            $messageBus: '@event.bus'
    App\Common\Application\Bus\Event\EventBus: '@App\Common\Infrastructure\Bus\Event\SymfonyEventBus'

    App\Common\Infrastructure\Bus\Command\SymfonyCommandBus:
        class: App\Common\Infrastructure\Bus\Command\SymfonyCommandBus
        arguments:
            $messageBus: '@command.bus'
    App\Common\Application\Bus\Command\CommandBus: '@App\Common\Infrastructure\Bus\Command\SymfonyCommandBus'

    App\Common\Infrastructure\Bus\Middleware\DoctrineTransactionMiddleware:
        class: App\Common\Infrastructure\Bus\Middleware\DoctrineTransactionMiddleware

    App\Common\Infrastructure\Bus\Middleware\DoctrineClearMiddleware:
        class: App\Common\Infrastructure\Bus\Middleware\DoctrineClearMiddleware

    # Controller
    App\Catalog\Infrastructure\Port\In\Controller\ProductController:
        class: App\Catalog\Infrastructure\Port\In\Controller\ProductController

    # Event store
    App\Common\Infrastructure\Port\Out\EventStore\EventStore:
        class: App\Common\Infrastructure\Port\Out\EventStore\EventStore
    App\Common\Domain\Event\EventStore: '@App\Common\Infrastructure\Port\Out\EventStore\EventStore'

    # Aggregate Repository
    App\Catalog\Infrastructure\Persistence\Product\ProductRepository:
        class: App\Catalog\Infrastructure\Persistence\Product\ProductRepository
    App\Catalog\Domain\Product\ProductRepository: '@App\Catalog\Infrastructure\Persistence\Product\ProductRepository'

    # Projection
    App\Catalog\Infrastructure\Persistence\Projection\DoctrineOrmProductProjectionRepository:
        class: App\Catalog\Infrastructure\Persistence\Projection\DoctrineOrmProductProjectionRepository

    App\Catalog\Infrastructure\Persistence\Projection\DoctrineOdmProductProjectionRepository:
        class: App\Catalog\Infrastructure\Persistence\Projection\DoctrineOdmProductProjectionRepository

    app.catalog.Infrastructure.persistence.projection.doctrine_orm_product_projector:
        class: App\Catalog\Infrastructure\Persistence\Projection\ProductProjector
        arguments:
            $productProjectionRepository: '@App\Catalog\Infrastructure\Persistence\Projection\DoctrineOrmProductProjectionRepository'

    app.catalog.Infrastructure.persistence.projection.doctrine_odm_product_projector:
        class: App\Catalog\Infrastructure\Persistence\Projection\ProductProjector
        arguments:
            $productProjectionRepository: '@App\Catalog\Infrastructure\Persistence\Projection\DoctrineOdmProductProjectionRepository'

    app.catalog.Infrastructure.persistence.projection.product_projector_collection:
        class: App\Common\Infrastructure\Persistence\Projection\ProjectorCollection
        arguments:
            $projectors:
                - '@app.catalog.Infrastructure.persistence.projection.doctrine_orm_product_projector'
                - '@app.catalog.Infrastructure.persistence.projection.doctrine_odm_product_projector'

    App\Catalog\Application\Projection\ProductProjectorMessageListener:
        class: App\Catalog\Application\Projection\ProductProjectorMessageListener
        arguments:
            $productProjectorCollection: '@app.catalog.Infrastructure.persistence.projection.product_projector_collection'

    App\Catalog\Application\Command\CreateProductHandler:
        class: App\Catalog\Application\Command\CreateProductHandler