# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\Common\Infrastructure\Bus\Event\SymfonyEventBus:
        class: App\Common\Infrastructure\Bus\Event\SymfonyEventBus
        arguments:
            $messageBus: '@event.bus'

    App\Common\Application\Bus\Event\EventBus: '@App\Common\Infrastructure\Bus\Event\SymfonyEventBus'

    # Controller
    App\Catalog\Infrastructure\Port\In\Controller\ProductController:
        class: App\Catalog\Infrastructure\Port\In\Controller\ProductController

    # Event store
    App\Common\Infrastructure\Port\Out\EventStore\EventStore:
        class: App\Common\Infrastructure\Port\Out\EventStore\EventStore
    App\Common\Domain\Event\EventStore: '@App\Common\Infrastructure\Port\Out\EventStore\EventStore'

    # Aggregate Repository
    App\Catalog\Infrastructure\Persistence\Product\ProductRepository:
        class: App\Catalog\Infrastructure\Persistence\Product\ProductRepository
    App\Catalog\Domain\Product\ProductRepository: '@App\Catalog\Infrastructure\Persistence\Product\ProductRepository'

    # Projection
    App\Catalog\Infrastructure\Persistence\Projection\ProductProjector:
        class: App\Catalog\Infrastructure\Persistence\Projection\ProductProjector
    App\Catalog\Application\Projection\ProductProjector: '@App\Catalog\Infrastructure\Persistence\Projection\ProductProjector'

    App\Catalog\Infrastructure\Persistence\Projection\DoctrineProductProjectionRepository:
        class: App\Catalog\Infrastructure\Persistence\Projection\DoctrineProductProjectionRepository
    App\Catalog\Application\Projection\ProductProjectionRepository: '@App\Catalog\Infrastructure\Persistence\Projection\DoctrineProductProjectionRepository'

    App\Catalog\Application\Projection\ProductProjectorMessageListener:
        class: App\Catalog\Application\Projection\ProductProjectorMessageListener
